### ISSUE TITLE
Error at path

### ISSUE THREAD

**Issue by Motytheultimate** [Bogdan-Lyashenko/codecrumbs#14]
hi there seems to be an error in your sidebar.js and a few more.
i tried it with running your project directly from your sources.

the error i get is the follwing

uncaught at reactOnSourceSet TypeError: Cannot read property 'path' of undefined
On example is at the follwing 

      <React.Fragment>
      <div>{file.path}</div>
      <div className={'copyIcon'}>
        <Copy copyText={file.path} />
      </div>
    </React.Fragment>

in sidebar js
[https://github.com/Bogdan-Lyashenko/codecrumbs/blob/master/src/public/js/components/sideBar/component/SideBar.js](url)

**Comment by Bogdan-Lyashenko** [comment]
Hi, can you please show how you run codedrumbs, especially `-e` param for entry file. I assume it can’t resolve it (and, yeah, I need to add better error handling). Thanks.

**Comment by Motytheultimate** [comment]
sure i have to add that i ran it using npm

"start:cc": "codecrumbs -e src/scripts/index.js -d src"

is my starting command

**Comment by Bogdan-Lyashenko** [comment]
Alright, you use windows os, right? Looks like there is an issue with paths handling. This is top prio, I will have a look ASAP. Will ping you when it’s fixed. Thanks again)

P.S. yeah.. I did all development on Mac, haven’t tested it on windows yet ;)

**Comment by Motytheultimate** [comment]
Sure glad to find these bugs.
it basically Looks like a very promising project so I'm Glad to help :)

**Comment by Bogdan-Lyashenko** [comment]
@Motytheultimate I fixed all (I hope 😸) bugs related to windows specifics, try version "1.0.22" (make sure to clear cache). Let me know if you still have issues. Thanks again, this was a really important issue to get aware of before 'going live". 👍

**Comment by Motytheultimate** [comment]
:) i'll try it later today

**Comment by Motytheultimate** [comment]
Looks like the path issue is fixed.

but now it throws an error at the dependecies option:

uncaught at reactByUpdatingFoldersState TypeError: Cannot read property 'dependencies' of undefined

at utils.js and on Tree.js

i think i should create a new issue?
