### ISSUE TITLE
Add Golang Support

### ISSUE THREAD

**Issue by morissette** [Bogdan-Lyashenko/codecrumbs#16]
Please add Golang support or comment on how to add support and I’ll add a PR.

**Comment by Bogdan-Lyashenko** [comment]
Hey, I assume it should be handled by fallback (fallback covers comments in code in // format). Have you tried it for Golang and it didn’t work? Thanks.

**Comment by morissette** [comment]
...checking...

**Comment by morissette** [comment]
Works.
