### ISSUE TITLE
cant get it started

### ISSUE THREAD

**Issue by nalagg** [Bogdan-Lyashenko/codecrumbs#17]
'codecrumbs' is not recognized as an internal or external command,
operable program or batch file.

created a dir '\devDependencies', ran yarn

**Comment by Bogdan-Lyashenko** [comment]
Hey, since you added it as dev dependency you need to add a command to “scripts” section in your package.json and then run it.
1) yarn add codecrumbs -D
2) add to package.json
“scripts”: {
“cc”: “codecrumbs -d src -e src/index.js”
}
3) in terminal run: yarn cc (or npm run cc)

**Comment by Bogdan-Lyashenko** [comment]
or you can use npx (https://github.com/zkat/npx)

**Comment by nalagg** [comment]
inside /src  i only see `index.dev.js`

**Comment by Bogdan-Lyashenko** [comment]
For what project are you trying to use it?
Let's do this example first to understand how everything works:
1) clone/download to your computer this project https://github.com/lucasbento/react-redux-todo (just as simple example)
2) install codecrumbs - `yarn global add codecrumbs`
3) go to the folder react-redux-todo (where you copied project from step 1)
4) run `codecrumbs -d src -e src/index.js`
5) go to the browser url http://localhost:2018 to see if it works

let me know if this works

**Comment by nalagg** [comment]
that worked,  thank you.  I cloned `https://github.com/Bogdan-Lyashenko/codecrumbs.git` and this gave problems.

**Comment by Bogdan-Lyashenko** [comment]
No worries, happy to help :)
