### ISSUE TITLE
Accept comments with spaces

### ISSUE THREAD

**Issue by hbarcelos** [Bogdan-Lyashenko/codecrumbs#2]
Currently, the following works:
```
//cc:authenticate#1;use case
```

But this way codecrumbs cannot detect the following:
```
// cc:authenticate#1;use case
```

Problem is that many popular linting rules for Javascript (like airbnb's or prettier) requires the space between the `//` and the comment.

If someone has auto-linting setup, then codecrumbs will not work.

**Comment by Bogdan-Lyashenko** [comment]
Yeah, that makes sense, thanks, will fix ASAP ;)
