### ISSUE TITLE
Only js supported? cpp? py?

### ISSUE THREAD

**Issue by xzcoin** [Bogdan-Lyashenko/codecrumbs#25]

**Comment by Zasch** [comment]
Readme states, that c++ and python are supported:

> Multi-language support
> Current version supports next programming languages:
> 
> JavaScript
> TypeScript
> Python
> PHP
> Java
> C++
> and others which use // as a comment :)
> Please file an issue to support other language you would like to have.

**Comment by Bogdan-Lyashenko** [comment]
Yep, check the Readme for languages support, it’s a big list, not only JavaScript ;)
