### ISSUE TITLE
Vue Support

### ISSUE THREAD

**Issue by ajerez** [Bogdan-Lyashenko/codecrumbs#26]
Any future plans to support Vue.js?
Thanks

**Comment by Bogdan-Lyashenko** [comment]
Hey, it supports any JavaScript :) Or what do you mean exactly by “support”? Thanks.

**Comment by ajerez** [comment]
I mean support for ".vue" files. I'm testing it with a Vue project and it stop showing the tree code for .vue files.

Nevermind it's a very good tool. Thanks for open sourcing it!

**Comment by Bogdan-Lyashenko** [comment]
Interesting. Yeah, you are right, it filters out that files. I can fix it, let’s keep this issue open. Thanks.

**Comment by ajerez** [comment]
Good, thanks!

**Comment by blackfyre** [comment]
I'm also interested in VueJS single file component support!
Is there anything implemented that could help us get started? (for example: a way to not ignore the *.vue files)

**Comment by Bogdan-Lyashenko** [comment]
Hi @blackfyre, it's quite easy actually https://github.com/Bogdan-Lyashenko/codecrumbs/blob/master/src/server/code-parse/language/index.js#L29, you just need to add `| vue` here. You can contribute/or I can try to find a minute to publish a fix today evening. Thanks.

**Comment by Bogdan-Lyashenko** [comment]
@blackfyre Thanks for the contribution ;) I published version with your fix; update to 1.6.1 to test. Let me know if you need anything else. Thanks.
