### ISSUE TITLE
Support Nodejs

### ISSUE THREAD

**Issue by joshuaalpuerto** [Bogdan-Lyashenko/codecrumbs#28]
Hi,

This project looks really cool! Sorry if am being dumb or not looking for more info. But I can't seems to work this with my [node-boilerplate](https://github.com/joshuaalpuerto/node-ddd-boilerplate). I added it as dependency and running it with this syntax.

```sh
$ npx codecrumbs -d src -e index.js
```

**Environment**
- Node/NPM - 10.7/6.1
- MACOS - Mojave(10.14.3)

**Comment by Bogdan-Lyashenko** [comment]
Hi, thanks for reporting) I will check, must be something simple, most likely with `-e index.index` (it’s ouside `src` direcory)

**Comment by Bogdan-Lyashenko** [comment]
Hey, @joshuaalpuerto can you please try to pull the latest version of codecrumbs and also use ‘container.js’(you have there) as entry point. So, run `codecrumbs -d src -e src/container.js`

**Comment by joshuaalpuerto** [comment]
@Bogdan-Lyashenko It works! May I know the reason why it needs to point to my `container.js`? Is it because thats where I wired app most of the code? Why it wont work on index? just curious. 

Thanks!

<img width="1112" alt="screen shot 2019-02-26 at 10 02 44 am" src="https://user-images.githubusercontent.com/7126484/53382006-b462a580-39ad-11e9-87e2-02e37d742d20.png">

**Comment by Bogdan-Lyashenko** [comment]
Hi there, because `index.js` was not child item of `src`. Everything there is built around tree-like data structure,`src` is root of the tree and all files (as well as entry point) must be inside of it in order to work ;)
