### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by TUPOBO** [Bogdan-Lyashenko/codecrumbs#29]
![image](https://user-images.githubusercontent.com/19498922/53214004-e7432b80-3685-11e9-9652-cd7a5a356d9c.png)

**Comment by Bogdan-Lyashenko** [comment]
Hi, thanks, probably you have much bigger project than I used for testing. Will fix that, need to change a way I do initial scanning of project structure.

**Comment by TUPOBO** [comment]
Thanks！

**Comment by chrisjibm** [comment]
Same here, running it on a mid-sized angular 6 app. Thanks for starting the project, looking forward to seeing it in action.

**Comment by wiecznyPoszukiwacz** [comment]
Make sure, you do not point codecrumbs to directory that contains node_modules dir.

**Comment by Bogdan-Lyashenko** [comment]
thanks, I will try to fix that ASAP.
@wiecznyPoszukiwacz thanks for pointing out, I actually now doubtful if I do filter `node_modules`, will make sure to do.

**Comment by Bogdan-Lyashenko** [comment]
@TUPOBO @chrisjibm I just published v1.1.1, it excludes `node_modules` (and few more fixes).
Can you please test and let me know it's fine now? If it's still failing I will think about chunking approach with reading files.

**Comment by Bogdan-Lyashenko** [comment]
@ar-naturalint FYI

**Comment by chrisjibm** [comment]
Sorry for delay, only just got to this. Thanks for the update, no more errors :)

**Comment by Bogdan-Lyashenko** [comment]
Awesome, thanks, closing the issue then ;)
