### ISSUE TITLE
Multiple crumbs in the same file

### ISSUE THREAD

**Issue by andrewmherren** [Bogdan-Lyashenko/codecrumbs#3]
It seems that currently only one crumb per file is supported, however it would be incredibly useful if there was a way to do multiple crumbs.

The particular use case I am thinking of is a file (like a reducer) that might be involved in more than one trail. 

PS Thanks for your work on this package, its a brilliant idea!

**Comment by Bogdan-Lyashenko** [comment]
@andrewmherren can you please share the code snipet how did you try it? It should support that, maybe a bug with parser for you particular case, need to see code to say more ;) Thanks 👍 
I tested on "single codecrumb"
```javascript

//cc:one
export const AuthState = new Record({
  authenticated: false,
  id: null
});

//cc:two
export function authReducer(state = new AuthState(), {payload, type}) {
  switch (type) {
    //cc:three
```
![image](https://user-images.githubusercontent.com/2098309/51202750-bf7edc00-18ff-11e9-90dc-5da6bf0ce76c.png)

And with "trail"
```javascript
      return state.merge({
        authenticated: !!payload, // cc:signin#3;toggle 'authenticated' flag
        id: payload ? payload.uid : null
      });

    case SIGN_OUT_SUCCESS:
      //cc:signin#2;sign out
```
![image](https://user-images.githubusercontent.com/2098309/51203009-5186e480-1900-11e9-903c-70b4182a0cb1.png)

I agree though, order of trailed crumbs inside one file can be messed up, need to fix that.

**Comment by andrewmherren** [comment]
@Bogdan-Lyashenko Interesting, I played with this some more and I seem to be getting intermittent behavior that is making things a little confusing. I documented what I tried and what the results were below to give you an idea of what i'm seeing but i'm not sure how actionable this is yet

I will try to put in some more time investigating this in the next couple days and see if I can come up with anything repeatable or if I can recreate anything similar in the demo project. I will also try a couple of other projects to see if maybe there is something special about this one in particular.

I started with this fairly simple component in my project and added a couple of trail beginnings and a regular (non trail) crumb. Its worth noting that I tried to setup the simplest test case I could but by having trails with only one point i'm probably hitting on a somewhat unexpected use case so maybe that is part of the problem.
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/9617845/51208818-8aed2f00-18c3-11e9-8dd8-8b5c5a684bf3.png">
When viewed in the browser it showed only the second trail:
<img width="811" alt="image" src="https://user-images.githubusercontent.com/9617845/51208751-5b3e2700-18c3-11e9-85db-c33bc44755e1.png">
after changing nothing but reloading http://localhost:2018 the trail menu changed slightly and the crumb display showed the step instead of the line number
<img width="810" alt="image" src="https://user-images.githubusercontent.com/9617845/51208779-714be780-18c3-11e9-8bf0-17996b5bb5aa.png">
I then noticed that some of your comments had trailing semicolons in the example and thought maybe that was effecting parsing so I edited the code to this:
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/9617845/51208981-f7682e00-18c3-11e9-9a49-0645b97c51dd.png">
and code crumbs auto updated (without refresh) to now add the -no trail- option but trail1 still wasnt showing.
<img width="893" alt="image" src="https://user-images.githubusercontent.com/9617845/51208941-de5f7d00-18c3-11e9-9184-7affd0f401f0.png">
Next I removed the semicolons again and tried removing my comment block at the top
<img width="730" alt="image" src="https://user-images.githubusercontent.com/9617845/51209561-5b3f2680-18c5-11e9-9798-dd9492996b66.png">
This gave tail1 and trail2 options but no opetion for -no trail-
<img width="803" alt="image" src="https://user-images.githubusercontent.com/9617845/51209517-42367580-18c5-11e9-9485-44ac0ae284ba.png">
Next I changed nothing and reloaded the browser but there was no change.
Then I tried adding the comment back in (just ctrl-z, ctrl-s)
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/9617845/51209789-ec160200-18c5-11e9-8a48-cdfcc5aee94b.png">
and this time it continues to show both trails but no option for -no trail-
<img width="807" alt="image" src="https://user-images.githubusercontent.com/9617845/51210300-42d00b80-18c7-11e9-9174-52ed011db3bb.png">

As I said, I'll see if I can do some more testing in the next couple of days and hopefully find more useful clues

**Comment by andrewmherren** [comment]
@Bogdan-Lyashenko Yes, I understand about only displaying one trail at a time and I totally see why you made that decision. 

I spent a little more time on this and I think I have found a pattern that may be useful. I think the issues I was having before were a combination of what you mentioned about crumbs near JSX but also what I will describe below.

It seems that maybe there is an issue around finding the end of a crumb. I found that if a crumb is followed by a comment (// or /**/ syntax) without at least one line of code between, the curmp will be missed. Here are a few examples using the demo project to better explain what I mean:

If i add a comment after the crumb in `exmaple-project/src/auth/actions.js` like this:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/9617845/51396382-d8e87980-1af3-11e9-9399-12222622fba5.png">
or like this:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/9617845/51396631-472d3c00-1af4-11e9-9fac-4af38113384b.png">
Then the associated step 1 crumb for the signin trail is no longer parsed
<img width="928" alt="image" src="https://user-images.githubusercontent.com/9617845/51396469-f87fa200-1af3-11e9-9689-947aca426a1c.png">

However a comment added before the crumb works just fine:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/9617845/51396792-aa1ed300-1af4-11e9-99a0-1f8bc7741fb9.png">
result:
<img width="939" alt="image" src="https://user-images.githubusercontent.com/9617845/51397133-68425c80-1af5-11e9-9ce1-a6f1ba7ff294.png">

Additionally, having at least one line of code between the crumb a comment works just fine:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/9617845/51397242-a3449000-1af5-11e9-9882-cef48cd541a2.png">
crumb displays correctly:
<img width="930" alt="image" src="https://user-images.githubusercontent.com/9617845/51397282-b8b9ba00-1af5-11e9-82af-c1e3ac21c6a0.png">

Lastly, all of the above conditions apply if the rather than a comment we add a second crumb
<img width="804" alt="image" src="https://user-images.githubusercontent.com/9617845/51397459-282fa980-1af6-11e9-912d-23a75ae3b066.png">
then the first crumb will be ignored but the second one will be displayed:
<img width="941" alt="image" src="https://user-images.githubusercontent.com/9617845/51397503-3d0c3d00-1af6-11e9-9493-78af3ebcff86.png">
If the order of the crumbs is swapped:
<img width="827" alt="image" src="https://user-images.githubusercontent.com/9617845/51397601-67f69100-1af6-11e9-8c94-1b90ffc77de1.png">
which ever one comes last is displayed:
<img width="932" alt="image" src="https://user-images.githubusercontent.com/9617845/51397587-60cf8300-1af6-11e9-978a-fbd5b43d105a.png">

And again, if there is at least one line of code between the crumbs:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/9617845/51397658-852b5f80-1af6-11e9-8c82-b44ec1443294.png">
then both are properly displayed
<img width="946" alt="image" src="https://user-images.githubusercontent.com/9617845/51397690-97a59900-1af6-11e9-9192-9a0d9dad4acf.png">

Now that I understand this it is easy to work around but it would be nice to be able to do something like:
```
//cc:signin#1;firebase sign in
//A detailed explanation about how this step of the trail works
//since the crumb name needs to be pretty short but the crumbs view
//in the sidebar will take people straight to the full comment
```

Anyway, I hope that is helpful and thank you again for your work on this amazing project. I am really excited to start using this in all of my projects!

**Comment by andrewmherren** [comment]
@Bogdan-Lyashenko I'd love to, I did a bit of digging around and found an existing ToDo comment that seems to resolve this issue so I created PR #11 

I'm new to contributing so i'm definitely up to any feedback you have! Thanks

**Comment by Bogdan-Lyashenko** [comment]
Answered in PR (and merged it ;)

**Comment by andrewmherren** [comment]
Thanks! I'll do a new PR implementing your loop suggestions this weekend if not sooner.

While doing this, I also noticed that the comments array includes both CommentLines `//style comments` and CommentBlocks `/* style comments */`. Currently code crumbs have to exist in CommentLines but i'm trying to think of a good way to take advantage of them in blocks as well. I'll probably submit a new issue for that in the next few days to get your input and maybe bounce some ideas back and forth if you're interested in adding support for that.

**Comment by Bogdan-Lyashenko** [comment]
Can your hold the thing with “block comment” for a while, I will need to write “stupid fallback parser” for other languages (like ruby, where I don’t have AST parser) first, so let’s keep it simple and then iterate. But you may close this issue (since you fixed it) and create one more for “block comments” - simply to not forget about that

**Comment by andrewmherren** [comment]
Ah yes, I can see how that will get tricky. Ok, will do. Thanks!
