### ISSUE TITLE
Wrong scroll position of code in Crumbs tab

### ISSUE THREAD

**Issue by dgreensp** [Bogdan-Lyashenko/codecrumbs#30]
I just started using codecrumbs, and I'm finding that the crumb code listings are not automatically scrolled to the crumb, they are scrolled to a vertical offset that is significantly smaller than the crumb offset, so that the crumb line is not visible unless I scroll it into view. :(

I peeked at the code, and the code for scrolling a crumb into view seems to hardcode a line height of 15.  In practice, the line height is 18 (font size of 12px and line height of 1.5).

**Comment by Bogdan-Lyashenko** [comment]
Thanks for reporting. Would you be interested to contribute the fix?

**Comment by dgreensp** [comment]
If I get time, perhaps!  What is the reasoning behind the original code, and where did that reasoning go wrong?  I wonder if it’s reasonable to measure the actual height of a line; I’d have to look at the code again to answer that.

**Comment by Bogdan-Lyashenko** [comment]
Hehe, hard to say now why it’s 15, but if it feels more like 18 - let’s make it 18. It’s not a big deal :)

**Comment by Bogdan-Lyashenko** [comment]
@oersted ok, sure, I'll push fix asap

**Comment by Bogdan-Lyashenko** [comment]
@oersted fixed, update to version 1.1.7 ;) let me know if it looks ok now. Thanks.

**Comment by Bogdan-Lyashenko** [comment]
@dgreensp FYI

**Comment by oersted** [comment]
Oh, that's brilliant! Thank you @Bogdan-Lyashenko. I'll check it asap.

**Comment by oersted** [comment]
Yep, it's perfect now :)

**Comment by Bogdan-Lyashenko** [comment]
Thanks :)
