### ISSUE TITLE
Codecrumbs views don't finish loading

### ISSUE THREAD

**Issue by adityavm** [Bogdan-Lyashenko/codecrumbs#31]
My Codecrumbs browser is in a perpetual loading state. I've added some logging on my end and it seems to be parsing the `//cc` comments properly, so I can't figure out why there is no visualisation.

*Browser*
<img width="974" alt="codecrumbs" src="https://user-images.githubusercontent.com/80849/53293033-9d427d00-3820-11e9-8b45-347b5fdf2dcf.png">

*Debug*
<img width="364" alt="parsed" src="https://user-images.githubusercontent.com/80849/53293049-e0045500-3820-11e9-8a8c-9c9d3506eb6e.png">

**Comment by Bogdan-Lyashenko** [comment]
Hi, can you please show your command how do you run it? (codedrumbs params). Also, which version do you use, please make sure it’s latest. Thanks.

**Comment by adityavm** [comment]
@Bogdan-Lyashenko no errors in the console:
<img width="612" alt="console" src="https://user-images.githubusercontent.com/80849/53296329-6ccf0300-3861-11e9-8650-51f6ec26f2c6.png">

and here's the command to run it. i've tried various entry points, none of them work:
<img width="565" alt="command" src="https://user-images.githubusercontent.com/80849/53296324-4f019e00-3861-11e9-9bff-e702e18b0987.png">

and the version is 1.1.1 (it's in the bottom left of the first screenshot 🙂)

**Comment by Bogdan-Lyashenko** [comment]
@adityavm for what project are you running codecrumbs?
Let's do this example to see how everything works:
1. clone/download to your computer this project https://github.com/lucasbento/react-redux-todo (just as simple example)
2. install codecrumbs - `yarn global add codecrumbs`
3. go to the folder react-redux-todo (where you copied project from step 1)
4. run `codecrumbs -d src -e src/index.js`
5. go to the browser url http://localhost:2018 to see if it works

let me know if this works and then we can continue from there.

**Comment by adityavm** [comment]
@Bogdan-Lyashenko it's a personal project. `react-redux-todo` works fine.
<img width="1119" alt="react-redux-todo" src="https://user-images.githubusercontent.com/80849/53296582-f2ed4880-3865-11e9-9ca7-383ed953bf23.png">

i also thought that it might be because of paths, however logging the paths from the different parser scripts seems to output the correct full path (second screenshot in this thread). i use absolute module paths, like:

`import Something from "component/Something";`

could that be an issue?

**Comment by Bogdan-Lyashenko** [comment]
> `import Something from "component/Something";`
> could that be an issue?
No, it should be fine, it might not be resolved by dependencies tree builder (Dependencies tab on UI) but it will not affect the entire picture.

So you ran codecrumbs for your project in the exact same way as you just did for  `react-redux-todo`  and it still doesn't work. That's super interesting... 👀 Alright, I will go through setup and add more error handling and logs. But basically, I assume it doesn't init here
https://github.com/Bogdan-Lyashenko/codecrumbs/blob/master/src/server/project-source/index.js#L75.

**Comment by adityavm** [comment]
@Bogdan-Lyashenko feel free to email me / ping me here if you need me to test out pre-release versions. codecrumbs looks super useful, so happy to help however 👍

**Comment by Bogdan-Lyashenko** [comment]
@adityavm hi there 🙂 I just pushed version with extra logs. When you have a free minute, can you please update to v1.1.2 (or higher) and run it again? So I covered with logs file structure parsing and also added log to browser to see what you are receiving in the end. Let's see 😸

**Comment by Bogdan-Lyashenko** [comment]
@adityavm try v1.1.4, should be golden now 😸

**Comment by adityavm** [comment]
@Bogdan-Lyashenko confirmed. works well. thank you!
