### ISSUE TITLE
C# Support

### ISSUE THREAD

**Issue by Horiuchihori** [Bogdan-Lyashenko/codecrumbs#32]
Would it be possible to support C#?
I'm developing game by Unity.
Best Regards

**Comment by Bogdan-Lyashenko** [comment]
Hey, sure ;)

**Comment by Bogdan-Lyashenko** [comment]
@Horiuchihori hi there 🙂 I've added C# support to v1.1.3, please update and try it out. Let me know if it works for you. Thanks for the help.

**Comment by Horiuchihori** [comment]
Wow! Thank you very match!!!
try tonight ;)

**Comment by Horiuchihori** [comment]
@Bogdan-Lyashenko I was Sccsessed. Thanks so match!
![2019-03-01 22 25 33](https://user-images.githubusercontent.com/41324614/53640993-07b84a80-3c71-11e9-96b2-e74ff5f15d1e.png)

**Comment by Horiuchihori** [comment]
fix #32
