### ISSUE TITLE
Kotlin Support

### ISSUE THREAD

**Issue by syo-sa1982** [Bogdan-Lyashenko/codecrumbs#33]
Hi.
Would it be possible to support Kotlin?
I'm  developing Android app by Kotlin.

I would be happy if you would consider it.
Thanking you in advance:)

**Comment by Bogdan-Lyashenko** [comment]
Hey, sure ;)

**Comment by Bogdan-Lyashenko** [comment]
@syo-sa1982 hi there 🙂 I've added Kotlin support to v1.1.3, please update and try it out. Let me know if it works for you. Thanks for the help.
