### ISSUE TITLE
Ruby Support

### ISSUE THREAD

**Issue by hbsyhjf** [Bogdan-Lyashenko/codecrumbs#34]
Would it be possible to support Ruby?
I have to understand a lot of Ruby sources written by others.
Best Regards

**Comment by Bogdan-Lyashenko** [comment]
Hey, sure ;)

**Comment by Bogdan-Lyashenko** [comment]
@hbsyhjf hi there 🙂 I've added Ruby support to v1.1.3, please update and try it out. Let me know if it works for you. Thanks for the help.

**Comment by hbsyhjf** [comment]
It works
Thank you very much..
