### ISSUE TITLE
hot reload does not work correctly when using typescript

### ISSUE THREAD

**Issue by lPaths** [Bogdan-Lyashenko/codecrumbs#37]
Whenever i save changes, codecrumbs still detect changes and recompile but the trail option on browser contain only current option, others are disappeared.

**Comment by Bogdan-Lyashenko** [comment]
Hi there, thanks for the report. Can you please show an example what several consecutive codedrumbs you wrote (and they didn’t appear together)? Are they part of one trail? Do they appear if you reload browser tab manually?
Thanks 🙂

**Comment by lPaths** [comment]
They are different trails. The trail options appear again if i reload browser tab manually.

**Comment by lPaths** [comment]
here's an example, i have 3 trails:
//cc:appmodule#1;something;+1
//cc:pipeline#1;something;+2
//cc:guard#1;somethingelse;+3
on browser, if i choose "appmodule", then make a change on project file then save it, pipeline and guard disappeared, only appmodule in trail option

**Comment by Bogdan-Lyashenko** [comment]
Yeah, I see, so here is the thing - it shows only one trail at the time. It’s kind of “feature” and not a bug ;) If you try
//cc:appmodule#1;first step
//cc:appmodule#2;second step
//cc:appmodule#3;third step
You will see these 3 steps.

**Comment by lPaths** [comment]
thank you for the answer :D
