### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by shafiev** [Bogdan-Lyashenko/codecrumbs#40]
Hello. Would it be possible to support Golang? i can also provide some support

**Comment by Bogdan-Lyashenko** [comment]
Hey, sure ;) it’s super simple, I can guide you if you are interested to contribute. Thanks.

**Comment by shafiev** [comment]
Ok please guide

**Comment by Bogdan-Lyashenko** [comment]
@shafiev Awesome!

Here is [commit](https://github.com/Bogdan-Lyashenko/codecrumbs/commit/d9e50dc4f9ebadf301fd6419da0ac75069a5e409) for adding `fortran` support (you can check it as an example).
Basically you need to do the next steps:
1) Add `go-lang.go` file with `Hello world` code and codecrumb-comment to `example-project/languages/` ([example](https://github.com/Bogdan-Lyashenko/codecrumbs/commit/d9e50dc4f9ebadf301fd6419da0ac75069a5e409#diff-5dfcf1fa76d6d0ad3a5f185c9c99c04d))
2) Create `src/server/code-parse/language/golang` folder with `codecrumbs.js` and `dependencies.js` file in it. ([examle](https://github.com/Bogdan-Lyashenko/codecrumbs/commit/d9e50dc4f9ebadf301fd6419da0ac75069a5e409#diff-370c69392708560d48e128c4c292a721))
3) In `src/server/code-parse/language/golang/codecrumbs.js` fix regex, if for `Golang` single line comment is `//` (same as for `JavaScript`) then regex will be `/^([^\/\/]*)\/\/(.*)$/`
4) Add mappings for file extensions to `src/server/code-parse/language/index.js` ([example](https://github.com/Bogdan-Lyashenko/codecrumbs/commit/d9e50dc4f9ebadf301fd6419da0ac75069a5e409#diff-29a210cf0591dd783e0fb5c690d27e5c))

To test:
1) In https://github.com/Bogdan-Lyashenko/codecrumbs/blob/master/src/index.dev.js#L3 replace: 
- `example-project/src-client` by `example-project/languages` 
- `example-project/src-client/index.js` by `example-project/languages/go-lang.go` 
2) run `yarn start`
3) go to localhost:2018

Let me know if it helps. Thanks.

**Comment by idoo** [comment]
@Bogdan-Lyashenko probably we could close it after merge https://github.com/Bogdan-Lyashenko/codecrumbs/pull/69
