### ISSUE TITLE
Lua suppport

### ISSUE THREAD

**Issue by shafiev** [Bogdan-Lyashenko/codecrumbs#41]
Hello.  Would it be possible to support Lua?

**Comment by Bogdan-Lyashenko** [comment]
Hey, sure ;)

**Comment by idoo** [comment]
@shafiev @Bogdan-Lyashenko please take a look https://github.com/Bogdan-Lyashenko/codecrumbs/pull/79/

**Comment by sigod** [comment]
@idoo Forgot to add Lua in the README.
