### ISSUE TITLE
only entry shown

### ISSUE THREAD

**Issue by aaronjensen** [Bogdan-Lyashenko/codecrumbs#45]
Hi there, I've tried running this on multiple codebases and I only ever see the entry. 

For example, from a pretty close to vanilla create-react-app:

<img width="1737" alt="Codecrumbs: better way to navigate the code maze! 2019-03-14 20-46-04" src="https://user-images.githubusercontent.com/8588/54407222-39320c80-469a-11e9-91c5-bd787cb148f6.png">

Is this the expected behavior or am I doing something wrong? Thanks!

**Comment by Bogdan-Lyashenko** [comment]
Hi there) First of all,  you need to enable “Source” toggle and “Codecrumbs” toggle. The idea is that it shows only “active” nodes, that means: from the cold start - it’s only entry point, then when you start putting codedrumbs in code (`//cc:test`) it will expand source tree and show files with codedrumbs as well. But you always can open all folders manually (by clicking on folders icons on diagram). Let me know if this helps, thanks.

**Comment by aaronjensen** [comment]
@Bogdan-Lyashenko Thank you, that helps. I was expecting the explorer to show everything, not just the nodes that were currently visible. I get it now, but it was definitely confusing at first, for what it's worth.

Cheers!
