### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by michaelkutuzov** [Bogdan-Lyashenko/codecrumbs#46]
Good evening!
I try to run your app for my project and get error from header of this issue.

Error from terminal:
<img width="1680" alt="1  bash 2019-03-15 23-29-03" src="https://user-images.githubusercontent.com/20220032/54460709-66a2b700-477b-11e9-9685-4a67e8c4cc7f.png">

Project structure and client.js:
<img width="1680" alt="~Documentsdevsnpfantasy-websitesrcclient js — fantasy-website 2019-03-15 23-30-54" src="https://user-images.githubusercontent.com/20220032/54460724-728e7900-477b-11e9-8714-a0734f671f5e.png">

What should I do to start cc correctly?
Thank you for answer.

**Comment by Bogdan-Lyashenko** [comment]
@michaelkutuzov hi there) It’s complaining about `...` operator, that means you have older Nodejs version. Please update Nodejs to the latest stable version and it should be fine. Let me know if it helps, thanks.

**Comment by michaelkutuzov** [comment]
Thank you! I tried to use 8.0.0. Installing 11.12.0 fixes the problem.
