### ISSUE TITLE
Haskell support

### ISSUE THREAD

**Issue by knl** [Bogdan-Lyashenko/codecrumbs#47]
Cool project!

Would it be possible to support Haskell? Comments in Haskell are:

```haskell
-- inline comment
{- block comment -}
```

**Comment by Bogdan-Lyashenko** [comment]
Hi, thanks) sure, will add to backlog.

**Comment by Bogdan-Lyashenko** [comment]
@knl Hi there. Added Haskell support, please update codecrumbs to version "1.2.4" (or higher). Please note currently codecrumbs-comments supported only for single-line (inline) comments.

Let me know if it works fine for you. Thanks 🙂
