### ISSUE TITLE
codecrumbs: command not found

### ISSUE THREAD

**Issue by pomfrida** [Bogdan-Lyashenko/codecrumbs#54]
![Screenshot 2019-05-03 at 11 43 27](https://user-images.githubusercontent.com/31915755/57130162-f4bd1600-6d98-11e9-9ce4-e8992148d598.png)

Tried following the tips in issue #17 - but I still can not use the codecrumbs command. 
Also tried updating "ecstatic" but I get the same warning. 
Any ideas what's going on here?

Edit: Noticed there's a typo in my screenshot. Also using command `codecrumbs -d src -e src/index.js` was not effective

**Comment by Bogdan-Lyashenko** [comment]
Maybe something with your permissions for global install, can you try to install to devDependencies instead?
1) run `yarn add codecrumbs -D` from terminal inside the project you want to use codecrumbs for
2) add `“cc”: “codecrumbs -d src -e src/index.js”` to “scripts” section in package.json
3) run `yarn cc` from terminal

**Comment by Bogdan-Lyashenko** [comment]
Let me know how it goes)

**Comment by pomfrida** [comment]
Thanks, that worked perfectly! 👍

**Comment by Bogdan-Lyashenko** [comment]
Awesome, closing the issue ;)
