### ISSUE TITLE
Corrupted Content Error

### ISSUE THREAD

**Issue by suntzuisafterU** [Bogdan-Lyashenko/codecrumbs#55]
Firefox displays this content when attempting to run codecrumbs against a simple, working react project.

Tested with 2 separate projects.

```
Corrupted Content Error

The site at http://localhost:2018/ has experienced a network protocol violation that cannot be repaired.

The page you are trying to view cannot be shown because an error in the data transmission was detected.

    Please contact the website owners to inform them of this problem.

```

I am not sure what additional information would be helpful.  I also tried this in Opera.  I am very interested in getting this working and any assistance will be appreciated.

**Comment by Bogdan-Lyashenko** [comment]
Hi there) Have you tried Chrome? Honestly I haven’t even tested any other browsers but Chrome :shrug:
Most likely it’s some “security” concerns Firefox apply, there is a work with filesystem and sockets communication, even though it’s on localhost Firefox might not trust it.

What OS is on your computer?
Can you also show how do you run codecrumbs?
Thanks

**Comment by suntzuisafterU** [comment]
Hi,

Just tried chrome, also whined about a network protocol/incorrect response.  OS is windows 10.  Startup command:

> λ codecrumbs -d src\ -e src\index.js
> >
> > Codecrumbs magic begins!
> >
> > started with options: {"entryPoint":"src\\index.js","projectDir":"src\\","clientPort":2018}
> - starting: mediator server
> + started: mediator server, listening: 3018
> - starting: http server for client assets
> - starting: source watcher
> + started: http server for client assets,  codecrumbs client is served on http://localhost:2018
> + started: source watcher: source-project-1558016214618 for: project:src\;  setup: dir - src\, entry point - src\index.js

**Comment by Bogdan-Lyashenko** [comment]
Just in case, what version of codedrumbs do you have?
Also, can you try to install codedrumbs as devDependency (`yarn add codecrumbs -D`). Let me know if it makes difference. Thanks.

**Comment by suntzuisafterU** [comment]
I have version 1.4.2

Tried adding as devDependency, same problem.  Would using npm as my package manager cause an issue?

**Comment by Trippnology** [comment]
I'm experiencing the same issue (also on Win10).

I've tried multiple browsers, but it seems the problem is a wonky redirect. Accessing the root returns a 302 with the location set to `//`:

![codecrumbs server redirect error](https://user-images.githubusercontent.com/846436/61806238-47a1e900-ae2f-11e9-883e-577c838bebae.png)

**Comment by suntzuisafterU** [comment]
@Trippnology Thanks for posting.  If  you find a solution please let me know.  I am very interested in using codecrumbs but this error has me beat.

Have you tried it on a different computer?  Which browsers have you tried? Also are you using npm?

**Comment by Bogdan-Lyashenko** [comment]
@suntzuisafterU @Trippnology it might be related to http-server package, some users also experience similar issue https://github.com/http-party/http-server/issues/525. I'll try to play with that a bit, will see if it help.

**Comment by Trippnology** [comment]
Yes, after reading that issue, it seems it's related to `ecstatic`, a dependency of the `http-server` module.

@suntzuisafterU A workaround to get you going (until this gets fixed upstream) is to install `http-server` v0.9.0 into codecrumbs install dir:

```
cd C:\Users\<your username>\AppData\Roaming\npm\node_modules\codecrumbs
npm i http-server@0.9.0
```

Any updates to codecrumbs will wipe out this change, so you may need to run this again in the future.

**Comment by Bogdan-Lyashenko** [comment]
@Trippnology thanks for confirming, I'll try to release package with fix today;

**Comment by Bogdan-Lyashenko** [comment]
@Trippnology @suntzuisafterU please try `codecrumbs@1.6.8` with a fix. Let me know if you still have issues, thanks ;)

**Comment by Trippnology** [comment]
Works great for me, thanks for the speedy response. I'll look forward to having a play with this nice project! 👍

**Comment by Bogdan-Lyashenko** [comment]
Awesome, thanks)
