### ISSUE TITLE
Java project doesnt work

### ISSUE THREAD

**Issue by josielesgoncalves** [Bogdan-Lyashenko/codecrumbs#62]
![codecrumbs](https://user-images.githubusercontent.com/16615558/58115103-ba90a880-7bcf-11e9-8e46-cb67c554b9c5.PNG)

Hi, I'm trying to test codecrumbs with my java project and its doesnt work.
When I ran codecrumbs, my console stops here.

**Comment by Bogdan-Lyashenko** [comment]
Hi, that’s fine, just open Chrome and go to localhost:2018 there :)

**Comment by josielesgoncalves** [comment]
I did it, but i have a ERR_INVALID_REDIRECT

**Comment by jackzBlog** [comment]
The same error

**Comment by Bogdan-Lyashenko** [comment]
Alright, seems like http-server issue https://github.com/http-party/http-server/issues/525; will try apply some of the suggestions

**Comment by Bogdan-Lyashenko** [comment]
@josielesgoncalves @jackzBlog please try `codecrumbs@1.6.8` with a fix. Let me know if you still have issues, thanks ;)

**Comment by jackzBlog** [comment]
@Bogdan-Lyashenko Awesome, It works.
