### ISSUE TITLE
Customizing Flow Chart

### ISSUE THREAD

**Issue by faridsabitov** [Bogdan-Lyashenko/codecrumbs#67]
Hi Bogdan!

First of all, thank you for such an amazing tool! I spent more than 20 mins trying to find of how to customize flow chart.

I'm interested in these examples:
- https://github.com/Bogdan-Lyashenko/js-code-to-svg-flowchart/tree/master/docs/examples/one-module-presentation
- https://github.com/Bogdan-Lyashenko/js-code-to-svg-flowchart/tree/master/docs/examples/blur-shape-branch

But can't specify these parameters. Where I can do that?

All the best,
Farid

**Comment by Bogdan-Lyashenko** [comment]
Hi, thanks) you mean if inside codedrumbs you want to see flowchart with different theme? No, it’s not possible right now. To be able to do so I probably need to introduce config file for codedrumbs (since it’s gonna be too much for cli param). It would be awesome If you are up for contribution ;)

**Comment by faridsabitov** [comment]
Thank you but I'm not a developer and that will be a lot harder for me :D Thank you for the tool!
