### ISSUE TITLE
Dependencies are not resolved at all.

### ISSUE THREAD

**Issue by bm-stschneider** [Bogdan-Lyashenko/codecrumbs#78]
In a barrel file with only dependencies I get this.
![image](https://user-images.githubusercontent.com/30625381/61629860-61ec9300-ac86-11e9-9921-0deac1f66d58.png)

**Comment by idoo** [comment]
@bm-stschneider what language are you inspecting?

**Comment by bm-stschneider** [comment]
JavaScript

**Comment by Bogdan-Lyashenko** [comment]
@bm-stschneider we use https://github.com/pahen/madge to resolve dependencies, and, we are aware it doesn't work in 100% cases. Can you show maybe one import line you have there, just to get to know if it's webpack alias/any other tricky import.

**Comment by bm-stschneider** [comment]
no its plain simple `import something from './something'` nothing fancy. does depcruiser provide the same result?

**Comment by bm-stschneider** [comment]
madge returns the same result

**Comment by bm-stschneider** [comment]
And another thing, in the tree I can see the dependency :P

**Comment by bm-stschneider** [comment]
Ok now it seems to work no idea why

**Comment by bm-stschneider** [comment]
is madge a peer dependecy? I had not installed madge before.

**Comment by Bogdan-Lyashenko** [comment]
@bm-stschneider no it's not peer dependecy; as I said previously - "dependencies" feature requires much more work to be "really working"; it's not prio right now since it's only supported for JavaScript and we still have many improvements to do for cross-language features :)
